name: 🟩 Auto Daily Commit

on:
  schedule:
    - cron: '0 7 * * *'  # Tous les jours à 7h00 UTC
  workflow_dispatch:       # Permet aussi de lancer manuellement
  push:                    # Se relance à chaque push pour rester actif
    branches:
      - master

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "hermannbrice12"
          git config user.email "hermannbrice12@users.noreply.github.com"

      - name: Update activity log
        run: |
          mkdir -p logs
          echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Daily auto-commit - tower-ansible-demo" >> logs/activity.log

      - name: Commit and push
        run: |
          git add logs/activity.log
          git diff --staged --quiet && echo "Nothing to commit" || (git commit -m "Update daily-activity-log"

  keep-alive:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Keep workflow alive
        uses: gautamkrishnar/keepalive-workflow@master
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
