name: log

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:      

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "hermannbrice12"
          git config user.email "hermannbrice12@users.noreply.github.com"

      - name: Update activity log
        run: |
          mkdir -p logs
          echo "[$(date '+%Y-%m-%d %H:%M:%S')]  tower-ansible-demo" >> logs/activity.log

      - name: Commit and push
        run: |
          git add logs/activity.log
          git commit -m "activitylog - $(date '+%Y-%m-%d')"
          git push
